module.exports = {
    additionalStylesheets: [],
    attributes: {
        alt: 'alt',
        disabled: 'disabled',
        href: 'href',
        id: 'id',
        src: 'src',
        title: 'title',
        checked: 'checked',
        type: 'type',
        for: 'for',
        placeholder: 'placeholder',
        value: 'value',
    },
    cascadeClass: undefined,
    componentsFolder: 'test/project',
    contextualClasses: [],
    name: undefined,
    namespace: undefined,
    pattern: 'bem',
    strict: true,
    text: 'The quick brown fox jumps over the lazy dog',
    themeClass: 'theme',
    backgroundClass: 'background',
    tags: {
        button: 'button',
        input: 'input',
        select: 'select',
        option: 'option',
        a: 'a',
        link: 'a',
        ul: 'ul',
        li: 'li',
        label: 'label',
        paragraph: 'p',
    },
};
